Repository conan-io/docs, pull requests merged in 2018-07, with the labels that each got.

#717 remote list --raw
  changelog.rst
  reference/commands/misc/remote.rst
Labels: in review

#660 Visual Studio generator uses $(USERPROFILE) macro
  changelog.rst
Labels: in review

#721 Proof reading
  introduction.rst
Labels: contributor pr

#720 Adds new filename parameter to tools.get()
  changelog.rst
  reference/tools.rst
Labels: in review

#723 Small change to verify the process
  installation.rst
Labels: contributor pr

#725 Docs for xz unzip
  changelog.rst
  reference/tools.rst
Labels: in review

#724 docs for run_environment=True
  changelog.rst
  devtools/running_packages.rst
  howtos/manage_shared_libraries/env_vars.rst
  reference/build_helpers/run_environment.rst
  reference/conanfile/other.rst
Labels: in review

#728 Review "Define ABI compatibility" section and documented requires modes
  creating_packages/define_abi_compatibility.rst
Labels: in review

#729 Propagated keep_permissions and pattern parameters from tools.get() to tools.unzip()
  changelog.rst
  reference/tools.rst
Labels: in review

#731 Line from config.rst missing in official docs. (second try)
  reference/commands/consumer/config.rst
Labels: contributor pr

#727 Framework search paths
  changelog.rst
  howtos/link_apple_framework.rst
  reference/generators/xcode.rst
Labels: in review

#732 Moved Conan 1.0 section to FAQ
  conf.py
  faq.rst
  faq/conan1.0.rst
  index.rst
Labels: in review

#733 Documents conan --test and should_test
  changelog.rst
  reference/commands/development/build.rst
  reference/conanfile/attributes.rst
Labels: in review

#735 tools.unix2dos() and tools.dos2unix() changelog
  changelog.rst
  conan1.0.rst
  reference/tools.rst
Labels: in review

#736 Updated conan upload examples in reference
  reference/commands/creator/upload.rst
Labels: in review

#737 Generate PDF docs for each version
  .travis.yml
  README.md
  _themes/conan/versions.html
  deploy_gh_pages.py
  uploading_packages.zip
Labels: enhancement, in review

#739 Suggestions to main Install page in documentation.
  installation.rst
Labels: contributor pr

#742 Added tools.run_environment(), conan config install --type
  reference/commands/consumer/config.rst
  reference/conanfile/other.rst
  reference/tools.rst
Labels: in review

#743 Feature/changelog
  changelog.rst
Labels: in review

#744 Release 1.6.0
  changelog.rst
  conan1.0.rst
  conf.py
  devtools/running_packages.rst
  faq.rst
  faq/conan1.0.rst
  howtos/link_apple_framework.rst
  howtos/manage_shared_libraries/env_vars.rst
  index.rst
  integrations.rst
  integrations/pylint.rst
  reference/build_helpers/run_environment.rst
  reference/commands/consumer/config.rst
  reference/commands/development/build.rst
  reference/commands/misc/remote.rst
  reference/conanfile/attributes.rst
  reference/conanfile/other.rst
  reference/generators/json.rst
  reference/generators/xcode.rst
  reference/tools.rst
Labels: in review

#746 [master] fix version link in PDF download
  _themes/conan/versions.html
Labels: in review

#747 [develop] fix version link in PDF download
  _themes/conan/versions.html
Labels: in review

#748 [release/1.5.2] fix version link in PDF download
  _themes/conan/versions.html
Labels: in review

#752 Feature/cmake deps path
  changelog.rst
  reference/build_helpers/cmake.rst
Labels: contributor pr

#756 Proofread and minor fixes for changes of Pull Request 744 of Conan 1.6
  changelog.rst
  faq/conan1.0.rst
  howtos/link_apple_framework.rst
  integrations/pylint.rst
  reference/build_helpers/run_environment.rst
  reference/commands/consumer/config.rst
  reference/commands/development/build.rst
  reference/conanfile/attributes.rst
  reference/conanfile/other.rst
  reference/tools.rst
  using_packages.rst
Labels: in review

#758 Added missing parameters to MSBuild() and fixed RunEnvironment link
  reference/build_helpers/run_environment.rst
  reference/build_helpers/visual_studio.rst
Labels: in review
