Repository conan-io/docs, pull requests merged in 2018-10, with the labels that each got.

#858 Encourage use of SPDX licenses in the "license" attribute of ConanFile
  reference/conanfile/attributes.rst
Labels: contributor pr

#863 Update cross_building.rst
  systems_cross_building/cross_building.rst
Labels: contributor pr

#862 Update package_dev_flow.rst
  developing_packages/package_dev_flow.rst
Labels: contributor pr

#849 Document CONAN_DEFAULT_PROFILE_PATH
  changelog.rst
  reference/config_files/default_profile.rst
  reference/env_vars.rst
Labels: in review

#843 tools.collect_libs now use self.cpp_info.libdirs
  reference/tools.rst
Labels: in review

#845 Docs gnu_triplet fix
  changelog.rst
  reference/tools.rst
Labels: in review

#857 Removed output parameter in latest_visual_studio_version_installed()
  changelog.rst
  reference/tools.rst
Labels: in review

#852 conanfile options and default_options documentation
  creating_packages/getting_started.rst
  creating_packages/package_repo.rst
  howtos/manage_shared_libraries/env_vars.rst
  integrations/clion.rst
  integrations/other.rst
  mastering/conanfile_py.rst
  mastering/conditional.rst
  mastering/policies.rst
  reference/build_helpers/autotools.rst
  reference/conanfile/attributes.rst
  reference/generators/compiler_args.rst
Labels: in review

#837 Document SVN for SCM
  changelog.rst
  creating_packages/external_repo.rst
  creating_packages/package_repo.rst
  reference/conanfile/attributes.rst
  reference/tools.rst
Labels: in review

#866 conan inspect
  reference/commands.rst
  reference/commands/misc/inspect.rst
Labels: in review

#868 Fix typo and structure in default profile section
  reference/config_files/default_profile.rst
Labels: in review

#834 Setting conditional default options
  reference/conanfile/attributes.rst
  reference/conanfile/methods.rst
Labels: in review

#870 [CI] Use Travis apt addon and cache to speed up builds
  .travis.yml
Labels: in review

#821 Documentation for --libdir in AutoTools
  changelog.rst
  reference/build_helpers/autotools.rst
  reference/build_helpers/cmake.rst
Labels: in review

#871 Fix sentence
  reference/build_helpers/cmake.rst
Labels: contributor pr

#876 Recovered 'Edit on GitHub' button
  conf.py
Labels: in review

#877 Fix CMake definitions table
  reference/build_helpers/cmake.rst
Labels: in review

#878 Minor changes regarding ConanInvalidConfiguration
  mastering/conditional.rst
  reference/conanfile/methods.rst
Labels: in review

#880 Plugin sections review
  extending/plugins.rst
  reference/plugins.rst
Labels: in review

#882 Use default_options as a dictionary in reference too
  reference/conanfile/attributes.rst
Labels: in review

#879 Use 'share' for DATAROOTDIR
  reference/build_helpers/autotools.rst
  reference/build_helpers/cmake.rst
Labels: in review

#883 Changelog for Conan 1.8.1
  changelog.rst
Labels: in review

#885 Fix docs about --sbindir and --libexecdir
  reference/build_helpers/autotools.rst
Labels: in review

#887 Example for SVN versioning
  howtos/capture_version.rst
Labels: in review

#884 Feature/rename docker images
  devtools/create_installer_packages.rst
  howtos/check_conan_version_in_conanfile.rst
  howtos/other_languages_package_manager/go.rst
  howtos/run_conan_in_docker.rst
  integrations/circleci.rst
  integrations/cmake/find_packages.rst
  integrations/gitlab.rst
  integrations/jenkins.rst
  reference/commands/misc/inspect.rst
  systems_cross_building/cross_building.rst
  uploading_packages/bintray/conan_center_guide.rst
Labels: in review

#892 Raise error with malformed table warning (with test)
  Makefile
  conf.py
  deploy_gh_pages.py
  make.bat
  make_mac.sh
Labels: in review

#891 Standarize experimental tags and warnings in all sections
  developing_packages/workspaces.rst
  extending/plugins.rst
  extending/python_requires.rst
  howtos/manage_cpp_standard.rst
  integrations/premake.rst
  reference/build_helpers/cmake.rst
  reference/commands/misc/inspect.rst
  reference/commands/output/install.rst
  reference/commands/output/upload.rst
  reference/commands/output/user.rst
  reference/generators/b2.rst
  reference/plugins.rst
Labels: in review

#894 Gitlab CI runner may need CONAN_USER_HOME set on Windows.
  integrations/gitlab.rst
Labels: contributor pr

#899 Changelog 1.8.3
  changelog.rst
  conf.py
  reference/conanfile/attributes.rst
Labels: in review

#900 Fix typos in the plugins doc
  extending/plugins.rst
  reference/plugins.rst
Labels: contributor pr

#901 Fixed commands help
  commands_help_update.py
  reference/commands/consumer/config.rst
  reference/commands/consumer/info.rst
  reference/commands/consumer/install.rst
  reference/commands/consumer/search.rst
  reference/commands/creator/export-pkg.rst
  reference/commands/creator/new.rst
  reference/commands/development/source.rst
  reference/commands/misc/alias.rst
  reference/commands/misc/help.rst
  reference/commands/misc/imports.rst
  reference/commands/misc/remove.rst
Labels: in review

#902 Document binary registry commands
  reference/commands/misc/remote.rst
Labels: in review

#893 Add docs about new fields in json output
  reference/commands/output/install.rst
Labels: in review

#904 Review visual studio build helpers section and SCons integration
  integrations/scons.rst
  reference/build_helpers/visual_studio.rst
  reference/tools.rst
Labels: in review

#907 Fix a/an grammar uses
  integrations/pkg_config_pc_files.rst
  reference/conanfile/attributes.rst
  reference/env_vars.rst
  reference/tools.rst
  uploading_packages/bintray/conan_center_guide.rst
Labels: contributor pr

#898 export-pkg using profile or settings by default
  developing_packages/package_dev_flow.rst
  integrations/clion.rst
  reference/commands/creator/export-pkg.rst
Labels: in review

#905 Proposed doc changes
  creating_packages/getting_started.rst
  getting_started.rst
  howtos/cmake_launch.rst
  mastering/custom_cache.rst
  reference/config_files/settings.yml.rst
Labels: contributor pr

#909 update and fix using packages
  reference/generators/visualstudiomulti.rst
  using_packages/conanfile_txt.rst
  using_packages/using_profiles.rst
  using_packages/workflows.rst
Labels: in review

#875 #874 Add tags attribute
  reference/commands/misc/inspect.rst
  reference/conanfile/attributes.rst
Labels: in review

#912 Docs for CONAN_USE_ALWAYS_SHORT_PATHS
  reference/config_files/conan.conf.rst
  reference/env_vars.rst
Labels: in review

#913 Updated upload json output
  reference/commands/output/upload.rst
Labels: in review

#915 Documentation for Conan client return codes
  reference/commands.rst
  reference/commands/return_codes.rst
Labels: in review

#917 conan tool update
  installation.rst
Labels: in review

#919 Renamed Plugins to Hooks
  extending.rst
  extending/hooks.rst
  reference.rst
  reference/commands/consumer/config.rst
  reference/config_files/conan.conf.rst
  reference/env_vars.rst
  reference/hooks.rst
Labels: in review

#918 Note about ConanInvalidConfiguration and its return code
  reference/commands/return_codes.rst
  reference/conanfile/methods.rst
Labels: in review

#914 VisualStudioBuildEnvironment constructor
  reference/build_helpers/visual_studio.rst
Labels: in review

#897 Add documentation for `conan remote clean`
  changelog.rst
  reference/commands/misc/remote.rst
Labels: in review

#926 new video
  videos.rst
Labels: in review

#922 Updated getting started with step by step instructions
  getting_started.rst
  howtos/manage_gcc_abi.rst
  uploading_packages/remotes.rst
Labels: enhancement, in review

#923 Review python 2 deprecation notice text
  installation.rst
Labels: in review

#896 - update premake documentation
  integrations/premake.rst
  reference/generators.rst
  reference/generators/premake.rst
Labels: in review

#932 Included swampUP 2018 videos, jfrog conan playlist and reviewed section
  videos.rst
Labels: in review

#931 Propagate defines in Premake example
  integrations/premake.rst
Labels: in review

#933 Added user and channel recommendations in FAQ
  faq/using.rst
  reference/conanfile/attributes.rst
Labels: in review

#934 Explicitly mention that remote name is uppercased
  reference/env_vars.rst
Labels: contributor pr
