Repository conan-io/docs, pull requests merged in 2018-02, with the labels that each got.

#509 Fix typo
  reference/generators/text.rst
Labels: [contributor pr]

#525 Added add to conan-center button image
  images/add_to_conan-center.png
  uploading_packages/bintray/conan_center_guide.rst
Labels: [in review]

#522 Alphabetic order to Environment Variable section
  reference/env_vars.rst
Labels: [in review]

#479 Feature/automatic pythonpath
  devtools/build_requires.rst
  howtos/python_code_reuse.rst
  reference/conanfile/attributes.rst
  reference/tools.rst
Labels: [in review]

#528 Introduction review
  getting_started.rst
  installation.rst
Labels: [in review]

#529 Fix typos on "using profiles" page
  using_packages/using_profiles.rst
Labels: [contributor pr]

#530 Avoid dangerous rm -rf
  using_packages/workflows.rst
Labels: [contributor pr]

#532 Added example of --verify-ssl option in conan config install
  reference/commands/consumer/config.rst
Labels: [in review]

#533 Update installation.rst
  installation.rst
Labels: [contributor pr]

#537 Added --verify-ssl feature to changelog
  changelog.rst
Labels: [in review]

#516 Add build_requires section to conanfile.txt reference
  reference/conanfile_txt.rst
Labels: [contributor pr]

#540 Removed conan-transit and added conan-community description
  changelog.rst
  getting_started.rst
  introduction.rst
  reference/commands/misc/remote.rst
  reference/config_files/registry.txt.rst
  uploading_packages/bintray/uploading_bintray.rst
  uploading_packages/remotes.rst
Labels: in review

#542 clarifying purpose of [build_requires] in conanfile.txt
  reference/conanfile_txt.rst
Labels: in review

#543 keep_path paramenter for copy inside imports()
  reference/conanfile/methods.rst
  reference/conanfile_txt.rst
Labels: in review

#544 Included description for inclusion requests image
  uploading_packages/bintray/conan_center_guide.rst
  uploading_packages/bintray/uploading_bintray.rst
Labels: in review

#545 Added dependents graph info to faq
  faq/using.rst
  images/conan_info_graph.png
Labels: in review

#539 Added method execution order for conan create
  reference/commands/consumer/install.rst
  reference/commands/creator/create.rst
Labels: in review

#546 Relative urls configuration
  changelog.rst
  uploading_packages/running_your_server.rst
Labels: in review

#547 Improved description of tools.environment_append()
  reference/tools.rst
Labels: in review

#526 compiler_args generator
  integrations.rst
  integrations/gcc.rst
  reference/generators.rst
  reference/generators/compiler_args.rst
  reference/generators/gcc.rst
Labels: in review

#548 stdcpp
  changelog.rst
  howtos.rst
  howtos/manage_cpp_standard.rst
  reference/build_helpers/autotools.rst
  reference/build_helpers/cmake.rst
  reference/conanfile/methods.rst
Labels: in review

#549 Package ID in the trace of package not found
  changelog.rst
  faq/troubleshooting.rst
Labels: in review

#550 Fix typo
  integrations/android_studio.rst
Labels: contributor pr

#541 Added new env variable CONAN_SYSREQUIRES_MODE
  changelog.rst
  reference/config_files/conan.conf.rst
  reference/env_vars.rst
Labels: in review

#551 skip devenv
  changelog.rst
  reference/config_files/conan.conf.rst
  reference/env_vars.rst
  reference/tools.rst
Labels: in review

#553 changelog for 1.1
  changelog.rst
  conf.py
  introduction.rst
Labels: in review

#554 fixes in changelog
  changelog.rst
Labels: in review

#555 Features documentation missing for 1.1 release
  reference/build_helpers/cmake.rst
  reference/commands/creator/test.rst
  reference/config_files/conan.conf.rst
  reference/env_vars.rst
Labels: in review

#557 Clarify Visual Studio integration docs
  integrations/visual_studio.rst
Labels: contributor pr
